---
include:
    - project: renovate-bot/renovate-runner
      file: /templates/renovate-config-validator.gitlab-ci.yml

include:
  - project: guardianproject-ops/projects
    ref: main
    file: terraform_templates/tf-module.gitlab-ci.yml
