---
include:
  - local: .gitlab-ci.local.yml
    rules:
      - exists:
        - .gitlab-ci.local.yml
  - project: renovate-bot/renovate-runner
    file: /templates/renovate-config-validator.gitlab-ci.yml
  - project: guardianproject-ops/projects
    ref: main
    file: terraform_templates/tf-module.gitlab-ci.yml
